POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "2025 year of closeness with God",
    "author": "Daniel",
    "url":"I shall be a friend of God in 2025",
    "likes": 9893903
}
